#!/usr/bin/env ruby
require 'set'

@changes = `git show --pretty="format:"  --name-only`.each_line.map {|line| line.delete!("\n") }
@rebuild = Set.new

def get_context(path)
  context = path.split('/').take(3)
  name = context.last.split('-').first
  version = context.last.split('-').last

  context_path = context.join('/')

  if File.exist?("#{context_path}/.requires")
    File.open("#{context_path}/.requires").each_line do |line|
      next if line == ""
      get_context(line)
    end
  end

  if @changes.any? { |c| c.include?(path) }
    docker_build(name, version, context_path)
  else
    docker_pull(name, version)
  end
end

def docker_build(name, version, context_path)
  if name == version
    @rebuild << "docker build --rm -t bugagazavr/#{name} #{context_path}"
  else
    @rebuild << "docker build --rm -t bugagazavr/#{name}:#{version} #{context_path}"
  end
end

def docker_pull(name, version)
  if name == version
    @rebuild << "docker pull bugagazavr/#{name}"
  else
    @rebuild << "docker pull bugagazavr/#{name}:#{version}"
  end
end

@changes.each do |line|
  context = line.split('/').first
  case context
  when 'services', 'langs'
    get_context(line)
  when 'base', 'circle.yml'
    @rebuild == Set.new(["docker build --rm -t bugagazavr/base base", @rebuild]).flatten
  end
end

require 'pp'
pp @rebuild

@rebuild.each do |cmd|
  system cmd
end